In [1]:
import os
os.chdir('/home/gebhart/projects/sheaf_kg')
import sheaf_kg.harmonic_extension as harmonic_extension
import numpy as np
from scipy import linalg

In [2]:
edge_index = np.array([[0, 1], [1, 2], [2, 3]], np.int)
edge_index = edge_index.T

In [3]:
ne = 10
de = 128
dv = 128
nv = ne+1
restriction_maps = np.random.randn(ne,2,de,dv)

In [4]:
def linear_chain(ne):
    edge_index = np.zeros((2,ne),dtype=np.int)
    for e in range(ne):
        edge_index[0,e] = e
        edge_index[1,e] = e + 1
    return edge_index


In [12]:
edge_index = linear_chain(ne)
edge_index

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [6]:
L = harmonic_extension.Laplacian(edge_index,restriction_maps)

In [7]:
B = np.array([0,ne],np.int)
U = np.array(range(1,ne),np.int)
xB = np.random.randn(dv*len(B))
xU = harmonic_extension.harmonic_extension(edge_index,restriction_maps,B,U,xB)

In [8]:
LSchur = harmonic_extension.Kron_reduction(edge_index, restriction_maps, B, U)

In [9]:
LSchur

array([[ 3.84367386e+01, -4.86147617e+00, -2.43540567e+00, ...,
         6.85414484e-01,  5.51769523e-01,  5.02474845e-02],
       [-4.86147617e+00,  2.42084633e+01,  2.63370551e+00, ...,
        -1.38170359e-01,  2.35284064e-02, -5.97827275e-02],
       [-2.43540567e+00,  2.63370551e+00,  4.41784899e+01, ...,
         6.01062403e-01,  2.65652887e-01, -2.14840101e-01],
       ...,
       [ 6.85414484e-01, -1.38170359e-01,  6.01062403e-01, ...,
         4.15304527e+01, -8.03075731e+00,  5.59938763e+00],
       [ 5.51769523e-01,  2.35284064e-02,  2.65652887e-01, ...,
        -8.03075731e+00,  4.93821141e+01, -5.37329399e+00],
       [ 5.02474845e-02, -5.97827275e-02, -2.14840101e-01, ...,
         5.59938763e+00, -5.37329399e+00,  3.33636109e+01]])

In [19]:
harmonic_extension.compute_costs(LSchur,[0],[1],np.random.randn(dv),np.random.randn(dv,10),dv)

array([11589.94522395,  7657.82197247, 10837.10992265,  9693.15174523,
        8277.34118152, 10731.32201729, 11421.16435575,  8062.01311711,
       11070.05133233, 10649.17286265])